@extends('layouts.app')
@section('title', 'Dashboard - FinanceHub')
@section('header-title', 'Dashboard')

@section('content')
<!-- View Sections Container -->
<div id="view-dashboard" class="view-section active" style="display: block;">
    <!-- Stats Grid -->
    <div class="stats-grid">
        <!-- Stat Card 1 -->
        <div class="stat-card">
            <div class="stat-header">
                <div class="stat-icon icon-blue">
                    <i class="ri-wallet-3-line"></i>
                </div>
                <span class="stat-title">Total Saldo</span>
            </div>
            <div class="stat-value">Rp {{ number_format($saldo, 0, ',', '.') }}</div>
        </div>

        <!-- Stat Card 2 -->
        <div class="stat-card">
            <div class="stat-header">
                <div class="stat-icon icon-green">
                    <i class="ri-arrow-left-down-line"></i>
                </div>
                <span class="stat-title">Total Pemasukan (Bulan Ini)</span>
            </div>
            <div class="stat-value">Rp {{ number_format($totalPemasukan, 0, ',', '.') }}</div>
        </div>

        <!-- Stat Card 3 -->
        <div class="stat-card">
            <div class="stat-header">
                <div class="stat-icon icon-red">
                    <i class="ri-arrow-right-up-line"></i>
                </div>
                <span class="stat-title">Total Pengeluaran (Bulan Ini)</span>
            </div>
            <div class="stat-value">Rp {{ number_format($totalPengeluaran, 0, ',', '.') }}</div>
        </div>
        
        <!-- Stat Card 4 -->
        <div class="stat-card">
            <div class="stat-header">
                <div class="stat-icon icon-purple">
                    <i class="ri-file-list-3-line"></i>
                </div>
                <span class="stat-title">Transaksi Bulan Ini</span>
            </div>
            <div class="stat-value">{{ $transaksiTerbaru->count() }} Transaksi</div>
        </div>
    </div>

    <!-- Charts Grid -->
    <div class="charts-grid">
        <!-- Line Chart -->
        <div class="chart-card line-chart-card">
            <div class="chart-header">
                <h3>Grafik Arus Kas ({{ $year }})</h3>
            </div>
            <div class="chart-container">
                <canvas id="cashflowChart"></canvas>
            </div>
        </div>

        <!-- Donut Chart -->
        <div class="chart-card donut-chart-card">
            <div class="chart-header">
                <h3>Kategori Pengeluaran (Bulan Ini)</h3>
            </div>
            <div class="chart-container donut-container">
                <canvas id="categoryChart"></canvas>
                <div class="donut-inner-text">
                    <span class="donut-label">Total</span>
                    <span class="donut-value">Rp {{ number_format($totalPengeluaran, 0, ',', '.') }}</span>
                </div>
            </div>
            <div class="chart-legend" id="donut-legend-container" style="margin-top: 15px;">
                <!-- Legend items generated by JS -->
            </div>
        </div>
    </div>

    <!-- Recent Transactions -->
    <div class="recent-transactions">
        <div class="section-header">
            <h3>Transaksi Terbaru</h3>
            <a href="/riwayat-transaksi" class="btn-outline">Lihat Semua</a>
        </div>
        
        <div class="transactions-list" style="margin-top: 15px;">
            @if($transaksiTerbaru->count() > 0)
                <table style="width: 100%; border-collapse: collapse;">
                    <thead>
                        <tr style="text-align: left; border-bottom: 1px solid var(--border-color);">
                            <th style="padding: 12px 15px; color: var(--text-muted); font-weight: 500;">Tanggal</th>
                            <th style="padding: 12px 15px; color: var(--text-muted); font-weight: 500;">Keterangan</th>
                            <th style="padding: 12px 15px; color: var(--text-muted); font-weight: 500;">Kategori</th>
                            <th style="padding: 12px 15px; color: var(--text-muted); font-weight: 500; text-align: right;">Jumlah</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($transaksiTerbaru as $trx)
                        <tr style="border-bottom: 1px solid var(--border-color);">
                            <td style="padding: 12px 15px;">{{ \Carbon\Carbon::parse($trx->tanggal)->format('d M Y') }}</td>
                            <td style="padding: 12px 15px;">{{ $trx->keterangan }}</td>
                            <td style="padding: 12px 15px;">
                                @if($trx->jenis_transaksi == 'Pemasukan')
                                    {{ $trx->akunKredit->kategori->nama_kategori ?? '-' }}
                                @else
                                    {{ $trx->akunDebit->kategori->nama_kategori ?? '-' }}
                                @endif
                            </td>
                            <td style="padding: 12px 15px; text-align: right; color: {{ $trx->jenis_transaksi == 'Pemasukan' ? '#10b981' : '#ef4444' }}; font-weight: 600;">
                                {{ $trx->jenis_transaksi == 'Pemasukan' ? '+' : '-' }} Rp {{ number_format($trx->jumlah, 0, ',', '.') }}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <p style="color: #8c9eae; font-size: 14px; padding: 20px 0; text-align: center;">Belum ada transaksi bulan ini.</p>
            @endif
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    // Cashflow Chart (Line/Area)
    const cashflowEl = document.getElementById('cashflowChart');
    if (cashflowEl) {
        const ctxLine = cashflowEl.getContext('2d');
        
        // Gradient for Pemasukan
        const gradientBlue = ctxLine.createLinearGradient(0, 0, 0, 400);
        gradientBlue.addColorStop(0, 'rgba(29, 78, 216, 0.2)');
        gradientBlue.addColorStop(1, 'rgba(29, 78, 216, 0)');

        // Gradient for Pengeluaran
        const gradientCyan = ctxLine.createLinearGradient(0, 0, 0, 400);
        gradientCyan.addColorStop(0, 'rgba(16, 185, 129, 0.2)');
        gradientCyan.addColorStop(1, 'rgba(16, 185, 129, 0)');

        const cashflowData = {!! json_encode($chartArusKas) !!};

        new Chart(ctxLine, {
            type: 'line',
            data: {
                labels: cashflowData.labels,
                datasets: [
                    {
                        label: 'Pemasukan',
                        data: cashflowData.pemasukan,
                        borderColor: '#1d4ed8', // Blue
                        backgroundColor: gradientBlue,
                        borderWidth: 2,
                        pointBackgroundColor: '#1d4ed8',
                        pointBorderColor: '#fff',
                        pointBorderWidth: 2,
                        pointRadius: 4,
                        fill: true,
                        tension: 0.4
                    },
                    {
                        label: 'Pengeluaran',
                        data: cashflowData.pengeluaran,
                        borderColor: '#10b981', // Green
                        backgroundColor: gradientCyan,
                        borderWidth: 2,
                        pointBackgroundColor: '#10b981',
                        pointBorderColor: '#fff',
                        pointBorderWidth: 2,
                        pointRadius: 4,
                        fill: true,
                        tension: 0.4
                    }
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'top',
                        align: 'start',
                        labels: {
                            usePointStyle: true,
                            boxWidth: 8,
                            boxHeight: 8,
                            color: '#64748b',
                            font: {
                                family: "'Inter', sans-serif",
                                size: 12
                            }
                        }
                    },
                    tooltip: {
                        mode: 'index',
                        intersect: false,
                        backgroundColor: '#1e293b',
                        titleFont: { family: "'Inter', sans-serif" },
                        bodyFont: { family: "'Inter', sans-serif" },
                        padding: 10,
                        cornerRadius: 8,
                        callbacks: {
                            label: function(context) {
                                let label = context.dataset.label || '';
                                if (label) {
                                    label += ': ';
                                }
                                if (context.parsed.y !== null) {
                                    label += new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(context.parsed.y);
                                }
                                return label;
                            }
                        }
                    }
                },
                scales: {
                    x: {
                        grid: { display: false, drawBorder: false },
                        ticks: { color: '#94a3b8', font: { family: "'Inter', sans-serif", size: 12 } }
                    },
                    y: {
                        grid: { color: '#f1f5f9', drawBorder: false, borderDash: [5, 5] },
                        ticks: {
                            color: '#94a3b8',
                            font: { family: "'Inter', sans-serif", size: 12 },
                            callback: function(value) {
                                if (value >= 1000000) {
                                    return (value / 1000000) + 'M';
                                } else if (value >= 1000) {
                                    return (value / 1000) + 'k';
                                }
                                return value;
                            }
                        }
                    }
                },
                interaction: {
                    mode: 'nearest',
                    axis: 'x',
                    intersect: false
                }
            }
        });
    }

    // Category Chart (Donut)
    const donutEl = document.getElementById('categoryChart');
    if (donutEl) {
        const ctxDonut = donutEl.getContext('2d');
        const kategoriPengeluaran = {!! json_encode($kategoriPengeluaran) !!};
        
        const labels = Object.keys(kategoriPengeluaran);
        const data = Object.values(kategoriPengeluaran);
        const total = data.reduce((a, b) => a + b, 0);
        
        const colors = ['#1d4ed8', '#10b981', '#60a5fa', '#34d399', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899'];
        
        // Generate legend HTML
        const legendContainer = document.getElementById('donut-legend-container');
        if (legendContainer && total > 0) {
            let legendHTML = '';
            labels.forEach((label, index) => {
                const value = data[index];
                const percentage = Math.round((value / total) * 100);
                const color = colors[index % colors.length];
                legendHTML += `
                    <div class="legend-item" style="display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 13px;">
                        <div style="display: flex; align-items: center; gap: 8px;">
                            <span style="display: inline-block; width: 10px; height: 10px; border-radius: 50%; background-color: ${color};"></span>
                            <span class="legend-label" style="color: var(--text-dark);">${label}</span>
                        </div>
                        <span class="legend-value" style="font-weight: 600;">${percentage}%</span>
                    </div>
                `;
            });
            legendContainer.innerHTML = legendHTML;
        } else if (legendContainer) {
            legendContainer.innerHTML = '<p style="text-align:center; color:var(--text-muted); font-size:13px;">Belum ada pengeluaran</p>';
        }

        new Chart(ctxDonut, {
            type: 'doughnut',
            data: {
                labels: labels,
                datasets: [{
                    data: data,
                    backgroundColor: colors.slice(0, labels.length),
                    borderWidth: 0,
                    hoverOffset: 4
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                cutout: '75%',
                plugins: {
                    legend: {
                        display: false // We use custom HTML legend
                    },
                    tooltip: {
                        backgroundColor: '#1e293b',
                        titleFont: { family: "'Inter', sans-serif" },
                        bodyFont: { family: "'Inter', sans-serif" },
                        padding: 10,
                        cornerRadius: 8,
                        callbacks: {
                            label: function(context) {
                                let label = context.label || '';
                                if (label) {
                                    label += ': ';
                                }
                                if (context.parsed !== null) {
                                    label += new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(context.parsed);
                                }
                                return label;
                            }
                        }
                    }
                }
            }
        });
    }
</script>
@endpush